import { PresetLocation } from "@/types";

export const PRESET_LOCATIONS: PresetLocation[] = [
  {
    id: "mumbai-mithi",
    name: "Mumbai (Mithi River Basin)",
    country: "India",
    description: "Dense coastal mega-city vulnerable to monsoon cloudbursts, high tidal surges, and river overflow.",
    center: { lat: 19.0760, lng: 72.8777 },
    defaultZoom: 13,
    boundingBox: {
      north: 19.120,
      south: 19.030,
      east: 72.930,
      west: 72.830,
    },
    disasterHistory: "2005 944mm torrential deluge disaster & recurrent monsoon inundations.",
  },
  {
    id: "valencia-turia",
    name: "Valencia (Turia River Basin)",
    country: "Spain",
    description: "Mediterranean basin subject to severe flash floods (DANA) with steep mountain runoff.",
    center: { lat: 39.4699, lng: -0.3763 },
    defaultZoom: 13,
    boundingBox: {
      north: 39.520,
      south: 39.420,
      east: -0.320,
      west: -0.440,
    },
    disasterHistory: "October 2024 catastrophic flash floods causing widespread infrastructure cutoff.",
  },
  {
    id: "houston-bayou",
    name: "Houston (Buffalo Bayou)",
    country: "USA",
    description: "Extremely flat topography with slow-draining bayou networks susceptible to hurricane rainfall.",
    center: { lat: 29.7604, lng: -95.3698 },
    defaultZoom: 13,
    boundingBox: {
      north: 29.810,
      south: 29.710,
      east: -95.300,
      west: -95.440,
    },
    disasterHistory: "Hurricane Harvey (2017) dropped over 1,300 mm of rain, flooding thousands of homes.",
  },
  {
    id: "kerala-chalakkudy",
    name: "Kerala (Chalakkudy Basin)",
    country: "India",
    description: "Steep Western Ghats runoff funneling into low-lying coastal backwaters.",
    center: { lat: 10.3060, lng: 76.3319 },
    defaultZoom: 13,
    boundingBox: {
      north: 10.360,
      south: 10.250,
      east: 76.390,
      west: 76.270,
    },
    disasterHistory: "2018 Great Kerala Floods where reservoir releases inundated river towns.",
  },
  {
    id: "rhine-ahr",
    name: "Ahr Valley (Rhine Basin)",
    country: "Germany",
    description: "Narrow V-shaped gorge where intense convective storms cause violent water surges.",
    center: { lat: 50.5432, lng: 7.1132 },
    defaultZoom: 13,
    boundingBox: {
      north: 50.590,
      south: 50.490,
      east: 7.180,
      west: 7.040,
    },
    disasterHistory: "July 2021 European floods with unprecedented river crest levels and bridge washouts.",
  },
  {
    id: "tokyo-edogawa",
    name: "Tokyo (Edogawa Basin)",
    country: "Japan",
    description: "Below sea-level zero-meter delta zone protected by hyper-engineered super levees.",
    center: { lat: 35.6967, lng: 139.8659 },
    defaultZoom: 13,
    boundingBox: {
      north: 35.740,
      south: 35.650,
      east: 139.920,
      west: 139.810,
    },
    disasterHistory: "Typhoon Hagibis (2019) testing major metropolitan flood diversion tunnels.",
  },
];
